version: "3.8"
services:
        app: 
          build: ./app
          links: 
            - db
          ports:
            - "5000:5000"
        db: 
          image: mysql:8.0
          ports: 
            - "32000:3306"
          environment: 
            MYSQL_ROOT_PASSWORD: 1
          volumes: 
            - ./db/alnafi.sql:/docker-entrypoint-initdb.d/alnafi.sql:ro


